# -*- coding: utf-8 -*-
"""Figure 1 v3 的图注、2.2 走读段与附录（原选窗图）图注，全部由 results/fig1_v3{TAG}_numbers.json 生成。
用法：python3 scripts/mk_fig1_text.py [TAG]   TAG='' 为随机窗版，'med' 为中位数窗版。"""
import json, os, sys
R = os.environ.get("S4ST_RESULTS", "results"); TAG = sys.argv[1] if len(sys.argv) > 1 else ""
d = json.load(open(f"{R}/fig1_v3{TAG}_numbers.json")); P2, P5 = d["P2"], d["P5"]; mode = "median" if TAG == "med" else "random"
rule = ("the window whose finest-band gap is closest to the median over all candidate windows of that section" if mode == "median"
        else f"a window drawn at random (seed {P2.get('seed', 0)}) from the candidate windows of that section")
cand = "candidate windows are $900\\,\\mu$m squares on a $160\\,\\mu$m step covering at least $85\\%$ of their area with at least three image clusters"
cap = (r"\caption{Two $900\,\mu$m windows, one from each Visium HD colon section, each " + rule + " (Appendix~\\ref{app:fig1sel} defines the candidates). " +
       r"\textbf{(a)} Rows one and three: H\&E, the measured field, the domain oracle and the trained model, projected on the first principal component of the $50$-gene panel, with each map's correlation to the measured map. Rows two and four: the finest band of each field (Section~\ref{sec:bands}). \textbf{(b)} Both predictors on each section's calibration curve (Section~\ref{sec:degen}). \textbf{(c)} The finest band's share of each field's variance over the whole test half. \textbf{(d)} The finest-band gap, model minus oracle, over all candidate windows of both sections, " + ("with each shown window marked; it sits at its section's median." if TAG == "med" else "with the shown windows (solid) and the medians (dotted).") + "}" "\n")
open("paper/fig1_caption.tex", "w").write(cap)
s2, s5 = P2["shown"], P5["shown"]; d2, d5 = P2["dist"], P5["dist"]
walk = (f"Figure~\\ref{{fig:blind}} previews the two readouts this section builds, on two $900\\,\\mu$m windows, one from each Visium HD colon section, with the predictors of Section~\\ref{{sec:exp}}, the domain oracle at $K = 20$ and a ridge model on frozen encoder features, scored on the held-out half of each section on a $50$-gene panel; each window is {rule}. "
        f"The first row of each window shows the measured field and the two predictions on the first principal component of the panel, each with its correlation to the measurement: the oracle is posterised into clusters and the model is continuous, and the two correlate with the measurement at ${s2['map_d']:.3f}$ against ${s2['map_r']:.3f}$ on the first section and ${s5['map_d']:.3f}$ against ${s5['map_r']:.3f}$ on the second. "
        f"The second row keeps only the finest band of Section~\\ref{{sec:bands}}: the measurement stays textured everywhere, the oracle keeps only cluster boundaries, and the model keeps a faint but correctly placed texture inside clusters; the correlations are ${s2['band_d']:.3f}$ against ${s2['band_r']:.3f}$ and ${s5['band_d']:.3f}$ against ${s5['band_r']:.3f}$. "
        f"Panel d places them among all ${d2['n']}$ and ${d5['n']}$ candidate windows, where the finest-band gap has median ${d2['gap_median']:.2f}$ and ${d5['gap_median']:.2f}$ and is positive in ${100*d2['frac_positive']:.0f}\\%$ and ${100*d5['frac_positive']:.0f}\\%$ of windows. "
        f"Panel b places both predictors on each section's calibration curve (Section~\\ref{{sec:degen}}), a monotone reparameterisation of the score by Proposition~\\ref{{prop:degen}}; panel c gives the finest band's share of each field's variance, ${100*P2['bpow']['truth']:.1f}\\%$ and ${100*P5['bpow']['truth']:.1f}\\%$ for the measurement against ${100*min(P2['bpow']['ridge'],P2['bpow']['dom20'],P5['bpow']['ridge'],P5['bpow']['dom20']):.1f}$--${100*max(P2['bpow']['ridge'],P2['bpow']['dom20'],P5['bpow']['ridge'],P5['bpow']['dom20']):.1f}\\%$ for either prediction.\n")
open("paper/fig1_walkthrough.tex", "w").write(walk)
L2, L5 = P2["largest"], P5["largest"]
appx = (r"\section{The largest-gap window}" "\n" r"\label{app:fig1sel}" "\n"
        f"Candidate windows for Figure~\\ref{{fig:blind}} are $900\\,\\mu$m squares on a $160\\,\\mu$m step covering at least $85\\%$ of their area with at least three image clusters. Figure~\\ref{{fig:blindsel}} repeats Figure~\\ref{{fig:blind}} for the window of each section with the largest finest-band gap among candidates whose two map correlations are both at least $0.80$ and within $8\\%$ of each other, the rule under which an earlier draft chose its opening figure. On the first section its gap is ${L2['band_r']-L2['band_d']:.3f}$ against a candidate median of ${d2['gap_median']:.3f}$, on the second ${L5['band_r']-L5['band_d']:.3f}$ against ${d5['gap_median']:.3f}$; map correlations are ${L2['map_d']:.3f}$ against ${L2['map_r']:.3f}$ and ${L5['map_d']:.3f}$ against ${L5['map_r']:.3f}$, finest-band correlations ${L2['band_d']:.3f}$ against ${L2['band_r']:.3f}$ and ${L5['band_d']:.3f}$ against ${L5['band_r']:.3f}$. It is an example of the contrast at its clearest, not a representative case; Figure~\\ref{{fig:blind}}d locates it in the distribution.\n"
        r"\begin{figure}[h]" "\n" r"\centering" "\n" r"\figorbox{figs/Fig1_iclr_v2.pdf}{Largest-gap window placeholder}" "\n" r"\caption{The two largest-gap windows, one per section, in the layout of Figure~\ref{fig:blind}a--c. Panel b is the calibration curve and panel c the finest-band variance shares of the whole test halves, as in Figure~\ref{fig:blind}.}" "\n" r"\label{fig:blindsel}" "\n" r"\end{figure}" "\n")
open("paper/fig1_appendix.tex", "w").write(appx); print(f"fig1 文本已生成（{mode}）：caption / walkthrough / appendix")
