# -*- coding: utf-8 -*-
"""附录：端到端超分方法（iStar）在 16 µm Xenium 上与 ridge 的比较。输入 results/istar_numbers.json（scripts/istar_agg.py）。输出 paper/istar_text.tex。"""
import json, os
R = os.environ.get("OCTAVE_RESULTS", "results"); o = json.load(open(f"{R}/istar_numbers.json"))
f3 = lambda a: f"${a['med']:.3f}$"; n = o["n_regions"]; ns = o["istar"]["pcc"]["n"]
has_h = "ridge_hipt" in o
hipt = ""
if has_h:
    h, h4 = o["ridge_hipt"], o["ridge_hipt_1e4"]
    dh_i = h['pcc']['med'] - o['istar']['pcc']['med']; db_i = h['beta1']['med'] - o['istar']['beta1']['med']
    rel = "slightly above iStar itself" if (dh_i > 0 and db_i > 0) else ("slightly below iStar itself" if (dh_i < 0 and db_i < 0) else "about level with iStar itself")
    hipt = (f" To separate the backbone from the method we also fit ridge on iStar's own HIPT features, sampled at the same bins on the same grid: it scores {f3(h['pcc'])} on the scalar and {f3(h['beta1'])} in the finest band ({f3(h4['pcc'])} and {f3(h4['beta1'])} with $\\lambda=10^4$), {rel} and far below ridge on Hibou-L features. "
            f"Most of the gap is therefore the backbone. The super-resolution head adds nothing over a linear readout of the same features. The finest band separates the two backbones by a factor of {o['ridge']['beta1']['med']/h4['beta1']['med']:.1f} at the same penalty. On the scalar the weaker backbone is only {100*(1-h4['pcc']['med']/o['ridge']['pcc']['med']):.0f}\\% behind, as a ratio of the two medians at the same penalty $\\lambda = 10^4$.")
txt = (r"\subsection{An end-to-end super-resolution method at $16\,\mu$m}" "\n" r"\label{app:istar}" "\n"
       f"Does a method built for fine structure beat the frozen-encoder ridge model in the finest band? iStar \\citep{{istar}} predicts expression at sub-spot resolution from H\\&E, through HIPT features and a small network. We ran it on the ${n}$ Xenium regions of the first release under a matched protocol: within each region a spatial half split with $320\\,\\mu$m blocks and a $64\\,\\mu$m exclusion buffer, the $200$ genes of Section~\\ref{{sec:xen}} as its training targets, its own feature extraction and training on the training half, and its super-resolved output averaged over the $3\\times3$ super-resolution cells around each held-out bin. Every predictor in Table~\\ref{{tab:istar}} is scored on the same bins with the same operator. "
       f"iStar reaches a median scalar score of {f3(o['istar']['pcc'])} against {f3(o['ridge']['pcc'])} for ridge on Hibou-L features. Its finest-band correlation is {f3(o['istar']['beta1'])} against {f3(o['ridge']['beta1'])}. It is below ridge on both in ${ns - o['istar_minus_ridge']['pcc']['above0']}$ of ${ns}$ specimens for the scalar and ${ns - o['istar_minus_ridge']['beta1']['above0']}$ of ${ns}$ for the finest band. Against the domain oracle ({f3(o['oracle']['pcc'])}, {f3(o['oracle']['beta1'])}) it is lower on the scalar and higher in the finest band. Its finest band holds {100*o['istar']['fine_share']['med']:.1f}\\% of its variance against {100*o['ridge']['fine_share']['med']:.1f}\\% for ridge and {100*o['truth_fine_share']['med']:.1f}\\% for the measurement, so the super-resolved field is smoother than the ridge prediction, not sharper. We also add spatial context to ridge: the mean features of the $8$ neighbours and of the second ring within $48\\,\\mu$m. This raises the scalar to {f3(o['context_ridge']['pcc'])} and the finest band to {f3(o['context_ridge']['beta1'])}, a small gain concentrated in the finest band.{hipt} "
       f"This is one method under one protocol. Another end-to-end design may still recover more fine structure. But a method whose stated purpose is resolution does not automatically score higher where resolution is measured. The scalar shows the gap but not its size. On the scalar iStar trails ridge by {100*abs(o['istar_minus_ridge']['pcc']['med'])/o['ridge']['pcc']['med']:.0f}\\%. In the finest band it trails by {100*abs(o['istar_minus_ridge']['beta1']['med'])/o['ridge']['beta1']['med']:.0f}\\%. Both are median paired shortfalls over specimens, taken against the median ridge score." "\n"
       r"\begin{table}[h]" "\n" r"\centering\small" "\n" r"\caption{An end-to-end super-resolution method against ridge on the Xenium regions, half split. Medians over specimens of per-specimen medians over regions, with the range over specimens; the last column is the finest band's share of each field's variance.}" "\n" r"\label{tab:istar}" "\n" r"\resizebox{\textwidth}{!}{\input{tab_istar}}" "\n" r"\end{table}" "\n")
open("paper/istar_text.tex", "w").write(txt); print("istar_text.tex 已生成", "(含 HIPT 对照)" if has_h else "(无 HIPT 对照)")
