# -*- coding: utf-8 -*-
"""附录：HEST（100 µm 间距）上的 OCTAVE 式差距。输入 results/hest_octave_delta.json（scripts/hest_octave_delta.py）。
输出 paper/tab_hestdelta.tex（跨 57 编码器的中位数与范围）与 paper/hestdelta_text.tex（段落，数字全部由此生成）。"""
import json, os, numpy as np
R = os.environ.get("S4ST_RESULTS", "results"); D = json.load(open(f"{R}/hest_octave_delta.json"))
A = {k: np.array([d[k] for d in D]) for k in D[0] if k != "enc"}; n = len(D)
med = lambda k: float(np.median(A[k])); lo = lambda k: float(A[k].min()); hi = lambda k: float(A[k].max())
rows = [("Scalar $\\mathrm{PCC}$, ridge", "pr"), ("Scalar $\\mathrm{PCC}$, domain oracle", "po"), ("Finest-band $\\beta_1$, ridge", "b1r"), ("Finest-band $\\beta_1$, domain oracle", "b1o")]
L = [r"\begin{tabular}{lrr}", r"\toprule", r"Quantity (cohort medians) & Median over %d encoders & Range \\" % n, r"\midrule"]
for lab, k in rows: L.append(f"{lab} & {med(k):.3f} & {lo(k):.3f}--{hi(k):.3f} \\\\")
L += [r"\midrule", f"Cohorts with oracle above ridge, scalar & {med('oracle_above_scalar'):.0f}/10 & {lo('oracle_above_scalar'):.0f}--{hi('oracle_above_scalar'):.0f} \\\\",
      f"Cohorts with oracle above ridge, finest band & {med('oracle_above_fine'):.0f}/10 & {lo('oracle_above_fine'):.0f}--{hi('oracle_above_fine'):.0f} \\\\",
      f"Finest-band width $\\sigma_1$ ($\\mu$m) & {med('sig1'):.1f} & {lo('sig1'):.1f}--{hi('sig1'):.1f} \\\\", r"\bottomrule", r"\end{tabular}"]
open("paper/tab_hestdelta.tex", "w").write("\n".join(L) + "\n")
n_fine_all = int((A["oracle_above_fine"] == 10).sum()); n_fine_maj = int((A["oracle_above_fine"] >= 6).sum())
n_scalar_all = int((A["oracle_above_scalar"] == 10).sum()); scalar_phrase = ("for every encoder" if n_scalar_all == n else ("for every encoder but one" if n_scalar_all == n - 1 else f"for {n_scalar_all} of the {n} encoders"))
txt = (r"\subsection{The benchmark's finest band}" "\n" r"\label{app:hestdelta}" "\n"
       f"Section~\\ref{{sec:exp:main}} measures the finest-band shortfall on Xenium, where the bins are $16\\,\\mu$m. The same computation on the benchmark, whose spots lie on a $\\sim\\!100\\,\\mu$m pitch, answers a natural question: does the benchmark's own finest band see anything the scalar does not? Table~\\ref{{tab:hestdelta}} gives the answer for all ${n}$ encoders, using the same domain oracle and the same operator as Appendix~\\ref{{app:protocol}}. The finest band on this pitch has a median width of ${med('sig1'):.0f}\\,\\mu$m, half the spot spacing, which is coarser than most of the tissue domains the oracle uses. The domain oracle is above the ridge model on the scalar in $10$ of $10$ cohorts {scalar_phrase}, and it stays above the model in the finest band as well, in a median ${med('oracle_above_fine'):.0f}$ of $10$ cohorts (range ${lo('oracle_above_fine'):.0f}$--${hi('oracle_above_fine'):.0f}$; ${n_fine_maj}$ of ${n}$ encoders have the oracle ahead in a majority of cohorts and ${n_fine_all}$ in all ten). The two shortfalls are of the same size, a median ${abs(100*med('ds')):.0f}\\%$ on the scalar and ${abs(100*med('df')):.0f}\\%$ in the finest band, both in the oracle's favour. Nothing here contradicts the Xenium result; it locates the benchmark's resolution. At $100\\,\\mu$m the finest accessible band is still at or above the scale of the domains, so a predictor that knows only domain identity wins at every scale the benchmark can resolve, and the structure inside domains that Section~\\ref{{sec:exp:main}} recovers at $10$--$30\\,\\mu$m is simply not measured. A benchmark on this pitch cannot directly validate it, however its score is read." "\n"
       r"\begin{table}[h]" "\n" r"\centering\small" "\n" r"\caption{Scale-resolved comparison of the domain oracle and the ridge model on the benchmark. Each entry is the median over cohorts of the per-sample value, then summarised over encoders. Ridge uses the cohort-selected penalty of Table~\\ref{tab:hestsummary}.}" "\n" r"\label{tab:hestdelta}" "\n" r"\input{tab_hestdelta}" "\n" r"\end{table}" "\n")
open("paper/hestdelta_text.tex", "w").write(txt); print(f"hestdelta: n={n}, σ1 {med('sig1'):.1f}, oracle>ridge fine 中位 {med('oracle_above_fine'):.0f}/10, 全 10/10 的编码器 {n_fine_all}, ≥6/10 的 {n_fine_maj}, Δs {100*med('ds'):.0f}% Δf {100*med('df'):.0f}%")
